### ISSUE TITLE
Implement Input Validation

### ISSUE THREAD

**Issue by NicNol** [NicNol/Commercial-Space-Flight-Tracker#30]
The mySQL server expects data passed to it to be of a certain type (see schema/ERD). The frontend should use HTML/JS to guide the user toward inputting valid data. It would prevent the user from submitting data that doesn't meet the database schema requirements.

"Our forms will accept all whitespace entries and we just error out if the datatype doesn't match the schema. "

**Comment by NicNol** [comment]
Example of input breaking:

![image](https://user-images.githubusercontent.com/28285920/156906995-55700e2a-4ac9-4611-83f3-d3ec4fb595d3.png)

**Comment by jlthompso** [comment]
The required fields in the form are accepting empty strings. I'm pretty sure this wasn't issue until I started pre-populating the forms with data for updates, but I haven't been able to find a working solution yet.

**Comment by NicNol** [comment]
#44
